/*
 * @(#)lua_binding_dll.h    generated by: makeheader    Thu Jun 22 14:18:07 2017
 *
 *		built from:	dll.ifc
 */

#ifndef lua_binding_dll_h
#define lua_binding_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE)
  #if defined(RTI_lua_binding_DLL_EXPORT)
    #define LUABINDINGDllExport __declspec( dllexport )
  #else
    #define LUABINDINGDllExport
  #endif /* RTI_lua_binding_DLL_EXPORT */

  #if defined(RTI_lua_binding_DLL_VARIABLE) 
    #if defined(RTI_lua_binding_DLL_EXPORT)
      #define LUABINDINGDllVariable __declspec( dllexport )
    #else
      #define LUABINDINGDllVariable __declspec( dllimport )
    #endif /* RTI_lua_binding_DLL_EXPORT */
  #else 
    #define LUABINDINGDllVariable
  #endif /* RTI_lua_binding_DLL_VARIABLE */
#else
  #define LUABINDINGDllExport
  #define LUABINDINGDllVariable
#endif /* RTI_WIN32 || RTI_WINCE */


#endif /* lua_binding_dll_h */
